## Galerkin Deep Neural Network

In [14]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from numsa.TFHessian import *
from random import *
from tqdm.notebook import tqdm

############| SETTINGS |############
N = 4; #Nuerons in the Hidden Layer
####################################

u = tf.keras.Sequential([
    tf.keras.layers.Dense(N,input_dim=1, activation='relu'),#Hidden Layer
    tf.keras.layers.Dense(1)#10 leyers weights.
])

print("u(0): ", u(tf.Variable([[0]])))
u.trainable_weights

u(0):  tf.Tensor([[0.]], shape=(1, 1), dtype=float32)


[<tf.Variable 'dense_29/kernel:0' shape=(1, 4) dtype=float32, numpy=
 array([[-0.51447636, -0.48145163,  0.3419479 , -0.18891168]],
       dtype=float32)>,
 <tf.Variable 'dense_29/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_30/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[ 0.03142762],
        [ 0.9790914 ],
        [-0.3134948 ],
        [ 0.8449639 ]], dtype=float32)>,
 <tf.Variable 'dense_30/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]